# Generated by Django 3.2.25 on 2026-08-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20260801_0941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='owner',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tags',
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(to='core.Tag'),
        ),
    ]
